docs/language/overview.md
Hi! Fixed small errors in comments. Thanks.
=> Fix some comments

README.md, docs/language/overview.md
=> fixed lifecycle

docs/language/overview.md
Fix typos and revert my mistake (ce7e3bd)
=> Fix typos in overview.md

docs/language/overview.md
Fixed a link to Section 0.10 from Section 6.6
=> Fixing link

docs/language/overview.md
You can see preview changes in my cloned repo: https://github.com/MairwunNx/BosqueLanguage/blob/example-codestyle-docs/docs/language/overview.md
I wrote this documentation according to the code already written in the **BosqueLanguage** repository and already guided by the existing repetitions of the code style.
Documentation may not be complete, because the code is still very small, and there is no official documentation. I think it would not be bad for the first time to merge my documentation, so that novices or those who want to try a language would write a code according to the style.
=> Docs: code-style addition for Highlight Features category.

ref_impl/src/ast/assembly.ts
=> Improved fix as suggested by clegoz

ref_impl/src/ast/parser.ts, ref_impl/src/test/regression_tests.ts, ref_impl/src/type_checker/type_checker.ts
Fixes #105
Changes:
Bad lamda infer on invoke -- did not index correctly for `this` parameter.
=> Fix for issue #105 -- bad lambda infer

ref_impl/src/compiler/mir_emitter.ts, ref_impl/src/interpreter/interpreter.ts, ref_impl/src/interpreter/value.ts, ref_impl/src/test/regression_tests.ts, ref_impl/src/type_checker/type_checker.ts
Fixes #106 
Changes:
Fixes to how vcall resolution is done.
=> Fix for vcall resolution

bosque-language-tools/language-configuration.json, bosque-language-tools/syntaxes/bosque.tmLanguage.json, ref_impl/src/ast/parser.ts
Reverts Microsoft/BosqueLanguage#115
Unit test breakage
=> Revert "Multiline comments"

docs/papers/publist.md
Changes:
Add new technical report on SafeStrings
=> Update publications with SafeStrings

ref_impl/src/core/core.bsq, ref_impl/src/interpreter/builtins.ts, ref_impl/src/test/basic_evaluation_test.ts
Changes:
- Extend String methods in entity definition
- New String methods:
- `reverse()`
- `upperCase()`
- `lowerCase()`
**Notes:**
- Im not sure if this is the correct way to implement new methods in core libs, let me know if your prefer another approach.
- Im not sure if my test methods are in the correct file or folder structure.
> This is my first contribution, please let me know about all my mistakes, after you agree with this PR, I may implement another useful methods for Arrays or Regex
=> String useful methods

bosque-language-tools/language-configuration.json, bosque-language-tools/syntaxes/bosque.tmLanguage.json, ref_impl/src/ast/parser.ts
Fixes #90.
Changes:
The fixed version of #115.
Line counter added for comments.
=> Fixed version of multiline comment

ref_impl/src/core/collections.bsq, ref_impl/src/interpreter/builtins.ts, ref_impl/src/test/basic_evaluation_test.ts
It kind of refers to #103 
Changes:
Added some useful methods to the List entity.
- `findLast()` returns the last element matching the predicate or throws an error if not found (inspired by Lodash)
- `tryFindLast()` is similar to the above one but it returns `none` if not found
- `fill()` simply fills the list with the given value (inspired by STL)
- `except()` returns a list which contains elements from the base list that are not present in the other list (inspired by LINQ)
Also, I fixed the description of `List::set` method (little typo).
Note:
This is my first PR so please let me know if I did anything wrong. I want to participate in this project so any guidelines will be much appreciated.
=> List useful methods

ref_impl/src/core/core.bsq, ref_impl/src/interpreter/builtins.ts, ref_impl/src/test/basic_evaluation_test.ts
Added math library with most used functions.
=> Added math helpers

ref_impl/src/test/basic_evaluation_test.ts, ref_impl/src/test/library_tests.ts, ref_impl/src/test/test_runner.ts
Changes:
Added library test file distinct from language tests.
=> Breaking library tests out into own test files

docs/language/overview.md, ref_impl/src/ast/body.ts, ref_impl/src/ast/parser.ts, ref_impl/src/ast/resolved_type.ts, ref_impl/src/test/basic_evaluation_test.ts, ref_impl/src/type_checker/type_checker.ts, ref_impl/src/type_checker/type_environment.ts
Fixes #24
Changes:
Code in parser, AST, type checker, and emitter to support structured assignments.
Test cases.
Documentation updates.
=> Structured assignment impl, tests, and docs

ref_impl/src/compiler/mir_cleanup.ts, ref_impl/src/compiler/mir_emitter.ts, ref_impl/src/compiler/mir_ops.ts, ref_impl/src/interpreter/interpreter.ts, ref_impl/src/type_checker/type_checker.ts
Fixes #16 
Changes:
Tidy up temp register emit and IR output.
=> Cleanup emit temp register output + misc fixes

docs/language/overview.md
Summary of changes to sections of `overview.md`:
**1.1** [nitpick] "a uber type" should be "an uber type"? 
**1.2.2** The word "tuples" used various times instead of "records" by accident/copy paste error a few times, unless I'm mistaken
**1.2.2** Closing square bracket on an example record `{f: Int, g: Bool]`
**1.3** Function return types missing for optional types example (unless this is allowed?) missing return value, unaligned subtype operator makes examples a little hard to read
**1.4** Concept types subtyping rule is backwards in the 'unless' comment on the last example. The example I used to convince myself was this:
```none
concept C1 {
field f: Int;
}
concept C2 {
field x: Double;
field f: Int;
}
// We have C2 <: C1
// C1 <: C1 + C2 is false even though C2 <: C1 as explained. { …
```
=> Fix typos/add corrections to overview.md

ref_impl/src/ast/assembly.ts, ref_impl/src/compiler/mir_cleanup.ts, ref_impl/src/compiler/mir_emitter.ts, ref_impl/src/compiler/mir_ops.ts, ref_impl/src/compiler/mir_ssa.ts, ref_impl/src/interpreter/interpreter.ts, ref_impl/src/interpreter/interpreter_environment.ts, ref_impl/src/type_checker/type_checker.ts
Fixes #17 
Changes:
Add SSA conversion step to MIR processing. 
Fix some bugs in Use/Mod & body processing.
=> Implement SSA conversion in MIR & fix minor issues

docs/language/overview.md, ref_impl/src/ast/assembly.ts, ref_impl/src/ast/parser.ts, ref_impl/src/test/basic_evaluation_test.ts, ref_impl/src/type_checker/type_checker.ts
Changes:
Simplify function subtyping.
Fix function invoke with multiple resolutions.
=> cleanup function subtyping + typechecking

ref_impl/.gitignore, ref_impl/src/compiler/ir_info.ts, ref_impl/src/compiler/mir_emitter.ts, ref_impl/src/compiler/mir_ops.ts, ref_impl/src/compiler/mir_ssa.ts, ref_impl/src/interpreter/interpreter.ts, ref_impl/src/test/ir_dumper.ts
Fixes #18 
Changes:
Improve MIR JSON dump
Add DGML IR output
Add command line IR dumper
Tidy IR manipulation
Cleanup SSA
=> Adding tools to simplify IR work, visualization, and SSA cleanup

ref_impl/src/compiler/mir_ops.ts
Changes:
Do xml encoding for DGML IR dump.
=> Fix xml encoding for DGML IR dump.

docs/language/overview.md, ref_impl/src/ast/body.ts, ref_impl/src/ast/parser.ts, ref_impl/src/test/basic_evaluation_test.ts, ref_impl/src/test/ir_dumper.ts, ref_impl/src/type_checker/type_checker.ts, ref_impl/src/type_checker/type_environment.ts
Fixes #74 and #26
Changes:
Add support for statement expressions (block, if, switch)
Add tests
Update docs
=> Support for statement expressions (block, if, switch)

ref_impl/src/test/regression_tests.ts, ref_impl/src/type_checker/type_checker.ts, ref_impl/src/type_checker/type_environment.ts
Fixes -- Flow sensitive typing incorrect propagation for argument and captured variables.
Changes:
Fix for type propagation
Test added
=> Fix for flow typing of argument and captured variables

README.md, ref_impl/src/compiler/bcgen.ts
Changes:
Rename compiler application to bcgen.
=> rename compiler to bcgen

README.md
Removing unwanted function closing braces
Fixes: MD file visibility fix
Changes:
- Fixed the function call closing extra braces.
=> Removed unwanted function closing

ref_impl/.gitignore, ref_impl/src/ast/assembly.ts, ref_impl/src/ast/parser.ts, ref_impl/src/compiler/bcgen.ts, ref_impl/src/compiler/mir_assembly.ts, ref_impl/src/compiler/mir_callg.ts, ref_impl/src/compiler/mir_emitter.ts, ref_impl/src/compiler/mir_ops.ts, ref_impl/src/core/core.bsq, ref_impl/src/interpreter/interpreter.ts, ref_impl/src/interpreter/value.ts, ref_impl/src/test/app_runner.ts, ref_impl/src/test/app_tests.ts, ref_impl/src/test/apps/tictactoe/main.bsq, ref_impl/src/test/basic_evaluation_test.ts, ref_impl/src/test/ir_dumper.ts, ref_impl/src/test/library_tests.ts, ref_impl/src/test/regression_tests.ts, ref_impl/src/type_checker/type_checker.ts, ref_impl/src/type_checker/type_environment.ts
=> Misc updates and improvements to core components from inital BMC work.

ref_impl/src/compiler/mir_assembly.ts, ref_impl/src/compiler/mir_emitter.ts, ref_impl/src/compiler/mir_ops.ts, ref_impl/src/compiler/mir_ssa.ts, ref_impl/src/compiler/mir_vartype.ts, ref_impl/src/type_checker/type_checker.ts
Update of IR to support future work.
=> Cleanup of IR to support Model Checker and AOT Compiler

ref_impl/src/runtimes/symtest/symtest.ts, ref_impl/src/test/tests/doc_examples/test.json, ref_impl/src/tooling/bmc/smtbody_emitter.ts
=> Bug fix for none check operation with KeyType

ref_impl/build/resource_copy.js, ref_impl/src/tooling/bmc/runtime/bin/macos/z3
=> Adding Z3 bins for Mac

ref_impl/src/core/direct/collections.bsq, ref_impl/src/runtimes/exegen/exegen.ts, ref_impl/src/tooling/aot/cppbody_emitter.ts, ref_impl/src/tooling/aot/cpptype_emitter.ts, ref_impl/src/tooling/aot/runtime/bsqvalue.h, ref_impl/src/tooling/bmc/smttype_emitter.ts
=> Misc bug fixes and updates

ref_impl/src/ast/assembly.ts, ref_impl/src/compiler/mir_assembly.ts, ref_impl/src/compiler/mir_emitter.ts, ref_impl/src/compiler/mir_ops.ts, ref_impl/src/core/direct/collections.bsq, ref_impl/src/test/tests/expression/objs.bsq, ref_impl/src/test/tests/expression/test.json, ref_impl/src/tooling/aot/cppbody_emitter.ts, ref_impl/src/tooling/aot/cppdecls_emitter.ts, ref_impl/src/tooling/aot/cpptype_emitter.ts, ref_impl/src/tooling/bmc/smtbody_emitter.ts, ref_impl/src/tooling/bmc/smttype_emitter.ts, ref_impl/src/type_checker/type_checker.ts
=> Basic support for OO features

ref_impl/src/core/direct/collections.bsq, ref_impl/src/test/runner.ts, ref_impl/src/test/tests/library/list.bsq, ref_impl/src/test/tests/library/map.bsq, ref_impl/src/test/tests/library/test.json, ref_impl/src/tooling/aot/cppbody_emitter.ts, ref_impl/src/tooling/aot/cppdecls_emitter.ts
=> Updates to collection libs + tests and fixes

impl/azure-pipelines.yaml, impl/package-lock.json, impl/src/runtimes/exegen/README.md, impl/src/runtimes/exegen/exegen.ts, impl/src/runtimes/vscmd/vscmd.ts, impl/src/test/test_runner.ts, impl/src/tooling/aot/runtime/bsqcustom/bsqlist_decl.h, impl/src/tooling/aot/runtime/bsqcustom/bsqlist_ops.h, impl/src/tooling/aot/runtime/bsqcustom/bsqmap_decl.h, impl/src/tooling/aot/runtime/bsqcustom/bsqmap_ops.h, impl/src/tooling/aot/runtime/bsqcustom/bsqset_decl.h, impl/src/tooling/aot/runtime/bsqcustom/bsqset_ops.h
Fixes: pipeline issues with GCC
=> tweaking pipeline

README.md, impl/src/core/cpp/core.bsq, impl/src/core/cpp/list.bsq, impl/src/core/symbolic/core.bsq, impl/src/core/symbolic/list.bsq, impl/src/test/tests/doc_examples/readme.bsq, impl/src/tooling/aot/cppbody_emitter.ts, impl/src/tooling/aot/runtime/bsqcustom/bsqlist_ops.h, impl/src/tooling/aot/runtime/bsqcustom/bsqmap_ops.h, impl/src/tooling/aot/runtime/bsqcustom/bsqset_ops.h, impl/src/tooling/bmc/smt_regex.ts, impl/src/tooling/bmc/smtbody_emitter.ts, impl/src/type_checker/type_checker.ts
=> Updates to quickly link in more collection code

bosque-language-tools/bsqdrop/ast/parser.js, impl/src/ast/parser.ts
Fixes Multi-line comment handling in parser
=> Fix multi-line comment regex

README.md, impl/src/tooling/aot/cppbody_emitter.ts
Fixes: Better overview of project in main readme.
=> Improved introduction to project and bugfix

impl/src/type_checker/type_checker.ts
Fixes undefined "$return" name when processing ensures clauses.
=> fix for special $return name in ensures clauses

.github/pull_request_template.md, README.md, bosque-language-tools/syntaxes/bosque.tmLanguage.json, docs/language/overview.md, impl/src/ast/parser.ts, impl/src/compiler/mir_ops.ts, impl/src/core/cpp/core.bsq, impl/src/core/cpp/list.bsq, impl/src/core/cpp/map.bsq, impl/src/core/cpp/set.bsq, impl/src/core/symbolic/core.bsq, impl/src/core/symbolic/list.bsq, impl/src/core/symbolic/map.bsq, impl/src/core/symbolic/set.bsq, impl/src/test/apps/angles/main.bsq, impl/src/test/apps/tictactoe/main.bsq, impl/src/test/tests/doc_examples/readme.bsq, impl/src/test/tests/expression/objs.bsq, impl/src/test/tests/expression/tuples.bsq, impl/src/test/tests/library/list.bsq, impl/src/test/tests/library/map.bsq, impl/src/test/tests/library/set.bsq, impl/src/test/tests/types/ooSubtype.bsq, impl/src/test/tests/types/primitiveSubtype.bsq, impl/src/test/tests/types/recordSubtype.bsq, impl/src/test/tests/types/tupleSubtype.bsq
(I can't resist one last big breaking change!)
=> Simplify method invoke syntax (from -> to simple .)

docs/language/overview.md, impl/src/core/cpp/list.bsq, impl/src/core/symbolic/list.bsq, impl/src/test/tests/doc_examples/langhighlight.bsq, impl/src/test/tests/doc_examples/test.json, impl/src/tooling/aot/cppbody_emitter.ts, impl/src/tooling/aot/cppdecls_emitter.ts, impl/src/tooling/aot/runtime/bsqcustom/bsqlist_ops.h, impl/src/type_checker/type_checker.ts
=> Updates, implementations, and tests for readme -- headline features

bosque-language-tools/bsqdrop/core/cpp/list.bsq, bosque-language-tools/bsqdrop/core/symbolic/list.bsq, impl/src/tooling/aot/cppbody_emitter.ts, impl/src/tooling/aot/runtime/bsqcustom/bsqlist_ops.h
Fixes Issues with "sum" missing and fixes some indexing issues.
=> Add list ops + fix indexing

impl/src/core/cpp/list.bsq, impl/src/core/symbolic/list.bsq, impl/src/tooling/aot/cppbody_emitter.ts, impl/src/tooling/aot/runtime/bsqcustom/bsqlist_ops.h, impl/src/tooling/bmc/smtbody_emitter.ts, impl/src/type_checker/type_checker.ts
Fixes #265 and others
Changes:
List<T>::ofType
List<T>::cast
Misc. Bugs
=> ofType, cast, and fixes

impl/src/runtimes/exegen/exegen.ts
Fixes https://github.com/microsoft/BosqueLanguage/issues/267
Changes:
This PR adds a new option to `exegen.js`: **-f --flags** to make it possible to pass custom flags to the compiler. 
```shell
exegen.js -h   
Usage: exegen [options]
Options:
-V, --version                 output the version number
-e --entrypoint [entrypoint]  Entrypoint of the exe (default: "NSMain::main")
-o --outfile [outfile]        Optional name of the output exe (default: "a.out")
-c --compiler [compiler]      Compiler to use (default: "clang++")
-l --level [level]            Build level version (default: "debug")
-f --flags <flags>            Custom compiler flags (default: "")
-h, --help                    output usage information
```
It also changes the handling of the Command object as it doesn't use the …
=> [tooling] add option to pass custom flags to compiler

impl/src/ast/parser.ts, impl/src/core/cpp/list.bsq, impl/src/core/symbolic/list.bsq, impl/src/test/tests/library/listtests.bsq, impl/src/test/tests/library/test.json, impl/src/tooling/aot/cppbody_emitter.ts, impl/src/tooling/bmc/smtbody_emitter.ts
=> Adding list tests and fixes

impl/src/core/cpp/list.bsq, impl/src/core/symbolic/list.bsq, impl/src/test/tests/library/listtests.bsq, impl/src/test/tests/library/test.json, impl/src/tooling/aot/cppbody_emitter.ts, impl/src/tooling/aot/runtime/bsqcustom/bsqlist_ops.h
=> Adding List<T> tests

impl/src/core/cpp/list.bsq, impl/src/core/symbolic/list.bsq, impl/src/test/tests/library/listtests.bsq, impl/src/test/tests/library/test.json, impl/src/tooling/aot/cppbody_emitter.ts, impl/src/tooling/aot/runtime/bsqcustom/bsqlist_ops.h, impl/src/tooling/bmc/smtbody_emitter.ts
=> More List<T>

impl/src/tooling/aot/cppbody_emitter.ts
=> Fix Enum constructor

impl/src/compiler/mir_emitter.ts, impl/src/tooling/aot/cppbody_emitter.ts, impl/src/type_checker/type_checker.ts
=> Fix to field ordering in entity/concept definitions

impl/src/ast/parser.ts, impl/src/tooling/aot/cpptype_emitter.ts, impl/src/type_checker/type_checker.ts
=> Fix ambig parse and bad coerce

impl/src/core/cpp/map.bsq, impl/src/core/symbolic/map.bsq, impl/src/test/tests/library/maptests.bsq, impl/src/test/tests/library/test.json, impl/src/tooling/aot/cppbody_emitter.ts, impl/src/tooling/aot/runtime/bsqcustom/bsqmap_ops.h, impl/src/tooling/bmc/smtbody_emitter.ts, impl/src/type_checker/type_checker.ts
=> Map<T> tests and fixes

impl/src/core/symbolic/keylist.bsq, impl/src/core/symbolic/map.bsq, impl/src/runtimes/exegen/exegen.ts, impl/src/runtimes/vscmd/vscmd.ts, impl/src/test/runner.ts, impl/src/test/tests/library/maptests.bsq, impl/src/test/tests/library/test.json, impl/src/tooling/aot/cppbody_emitter.ts, impl/src/tooling/aot/cpptype_emitter.ts, impl/src/tooling/aot/runtime/bsqcustom/bsqmap_ops.h, impl/src/tooling/bmc/smtbody_emitter.ts
=> Map<K, V> keys/values/entries

impl/src/core/cpp/map.bsq, impl/src/core/symbolic/list.bsq, impl/src/core/symbolic/map.bsq, impl/src/test/tests/library/listtests.bsq, impl/src/test/tests/library/test.json, impl/src/tooling/aot/cppbody_emitter.ts, impl/src/tooling/aot/runtime/bsqcustom/bsqlist_ops.h, impl/src/tooling/aot/runtime/bsqvalue.h, impl/src/tooling/bmc/smtbody_emitter.ts
=> List<T>::partition and fixes for ref counting

impl/src/core/cpp/list.bsq, impl/src/core/symbolic/list.bsq, impl/src/test/tests/library/listtests.bsq, impl/src/test/tests/library/test.json, impl/src/tooling/aot/cppbody_emitter.ts, impl/src/tooling/aot/runtime/bsqcustom/bsqlist_ops.h, impl/src/tooling/aot/runtime/bsqcustom/bsqmap_ops.h, impl/src/tooling/aot/runtime/bsqcustom/bsqset_ops.h
=> List<T> to map transforms

impl/src/compiler/mir_emitter.ts, impl/src/test/tests/library/listtests.bsq, impl/src/type_checker/type_checker.ts
=> Fixed pcode naming to be unique (even on same line)

impl/src/ast/assembly.ts
=> Fix field order from provides traversals

impl/src/core/cpp/list.bsq, impl/src/core/symbolic/list.bsq, impl/src/test/tests/library/listoptests.bsq, impl/src/test/tests/library/test.json, impl/src/tooling/aot/cppbody_emitter.ts, impl/src/tooling/aot/runtime/bsqcustom/bsqlist_ops.h
=> Add ListOf operations: zip, unzip, and range

docs/language/overview.md, impl/src/ast/parser.ts, impl/src/test/tests/doc_examples/langhighlight.bsq, impl/src/test/tests/doc_examples/test.json
=> Language highlights tests and fixes

impl/src/core/cpp/map.bsq, impl/src/core/symbolic/map.bsq, impl/src/test/apps/tictactoe/main.bsq
=> Cleanup of Tic-Tac-Toe code

impl/src/core/cpp/map.bsq, impl/src/core/symbolic/map.bsq, impl/src/test/tests/library/maptests.bsq, impl/src/test/tests/library/test.json, impl/src/tooling/aot/cppbody_emitter.ts, impl/src/tooling/aot/runtime/bsqcustom/bsqmap_ops.h, impl/src/tooling/aot/runtime/bsqcustom/bsqset_ops.h, impl/src/tooling/bmc/smtbody_emitter.ts
=> Map<K, V> union and merge ops

impl/src/compiler/mir_emitter.ts, impl/src/compiler/mir_ops.ts, impl/src/compiler/mir_vartype.ts, impl/src/core/cpp/core.bsq, impl/src/core/cpp/iteration.bsq, impl/src/core/symbolic/core.bsq, impl/src/core/symbolic/iteration.bsq, impl/src/test/apps/nbody/nbody.bsq, impl/src/tooling/aot/cppbody_emitter.ts, impl/src/tooling/aot/cpptype_emitter.ts, impl/src/tooling/aot/runtime/bsqvalue.h, impl/src/tooling/aot/runtime/common.h, impl/src/type_checker/type_checker.ts
=> Adding initial pass on Float64 and Iteration for nbody support

impl/src/ast/parser.ts, impl/src/ast/parser_env.ts, impl/src/tooling/aot/cppbody_emitter.ts, impl/src/tooling/aot/cppdecls_emitter.ts, impl/src/tooling/aot/cpptype_emitter.ts, impl/src/tooling/aot/runtime/bsqvalue.h, impl/src/type_checker/type_checker.ts
Lambda "this" capture
Forward decl of display
=> Fixes while working on nbody

Dockerfile, docs/extras/docker.md
Fixes https://github.com/microsoft/BosqueLanguage/issues/337
Changes:
This PR adds VSCode & Docker integration option for interested developers. This way they wouldn't have to manually clone, compile and install their development environments. Future updates could be integrated more easily as Docker would take care of these tasks. 
There is also a small readme in a new subdir `docs/extras/docker.md`.
=> added VSCode & Docker integration

impl/src/core/cpp/core.bsq, impl/src/core/symbolic/core.bsq, impl/src/core/verify/core.bsq, impl/src/tooling/aot/cppbody_emitter.ts
Fixes #349
Changes:
Added builtin methods for float to/from int conversion to core libraries (and implement for runtime).
=> Adding FP<->Int conversions

impl/src/core/cpp/core.bsq, impl/src/core/symbolic/core.bsq, impl/src/core/verify/core.bsq, impl/src/tooling/aot/cppbody_emitter.ts, impl/src/tooling/bmc/smtbody_emitter.ts
Fixes #351 
Changes:
Add Mod operator to symtest.
Improve precondition check in symtest and exegen.
=> Implement mod in checker and improve in compiler

impl/package.json, impl/src/runtimes/bsqcheck.ts, impl/src/tooling/icpp/interpreter/runner.cpp, impl/src/tooling/icpp/interpreter/runtime/bsqvalue.cpp, impl/src/tooling/icpp/interpreter/runtime/bsqvalue.h, impl/src/tooling/verifier/evaluator/decls.cpp
=> fixes for basic string

impl/src/core/verify/list.bsq, impl/src/runtimes/bsqcheck.ts, impl/src/test/smt_runner.ts, impl/src/tooling/icpp/interpreter/op_eval.cpp, impl/src/tooling/icpp/interpreter/runner.cpp, impl/src/tooling/icpp/interpreter/runtime/bsqvalue.cpp, impl/src/tooling/verifier/evaluator/decls.cpp, impl/src/tooling/verifier/evaluator/decls.h, impl/src/tooling/verifier/evaluator/workflows.cpp, impl/src/tooling/verifier/runtime/smtruntime.smt2, impl/src/tooling/verifier/smt_assembly.ts, impl/src/tooling/verifier/smt_workflows.ts, impl/src/tooling/verifier/smtbody_emitter.ts, impl/src/tooling/verifier/smtdecls_emitter.ts, impl/src/tooling/verifier/smttype_emitter.ts, impl/src/type_checker/type_checker.ts, impl/src/type_checker/type_environment.ts
Numerous bug fixes for misc. examples.
=> Misc bug fixes

impl/src/compiler/mir_emitter.ts, impl/src/test/tests/doc_examples/readme.json, impl/src/tooling/verifier/smtbody_emitter.ts
Adding broken lambda capture test as well -- need to fix as next step.
=> Misc fixes

README.md, impl/src/test/tests/doc_examples/data_invariants.txt, impl/src/test/tests/doc_examples/readme.json
Cleanup for DataType and invariant example in the readme
=> Data Type and Invariant
