README.md

In order to correctly install the language node.js and typescript need
to be present on the system.

Add Windows requirements

---

docs/language/overview.md

Fix a broken markdown link in overview.md in 0.7 None Processing

Fix typo in 0.7 None Processing

---

docs/language/overview.md

Changed title from "Compute Language" to just "Language" and fixed spellings of "flaky" and "indices".

Fix spellings in Overview

---

docs/language/overview.md

Separate PR from #63 because grammar's more subjective than typos.

Grammar tweaks in language/overview.md, section 5.3

---

docs/language/overview.md

Previously accessing index 1 yields value of index 0. Change index instead of result to be consistent with other access-operator sections.

Change sample index in section 5.9

---

docs/language/overview.md

Without semicolon at the end of the expression, it can confuse a novice reading the documentation. I think you need to follow the rules of good documentation.
I simply add semicolon to the end of the examples in the Lambda Constructors category.

Semicolon fix in Lambda Constructors examples.

---

README.md
ref_impl/src/core/core.bsq
ref_impl/src/test/apps/tictactoe/main.bsq

The **core.bsq** and **main.bsq** files were having extra empty lines, which are removed and cleaned-up. In addition to this the main **README.md** file is added with the prettify for the code-blocks using the TS syntax highlighting.

Cleanup: Trimmed unnecessary empty lines

---

.github/ISSUE_TEMPLATE/feature_request.md
bosque-language-tools/language-configuration.json

Comments aren't supported in JSON (see https://stackoverflow.com/questions/244777/can-comments-be-used-in-json).

Fix typo & delete comments in JSON files

---

.gitignore
ref_impl/src/ast/assembly.ts
ref_impl/src/compiler/mir_emitter.ts
ref_impl/src/test/regression_tests.ts
ref_impl/src/test/test_runner.ts

Fixes #111
Changes:
Strings have some special case logic to handle `String` and `String[T]` transparently to developers. This logic was missing on one path.

Fix for special string handling issue #111

---

ref_impl/src/ast/body.ts
ref_impl/src/ast/parser.ts
ref_impl/src/compiler/mir_emitter.ts
ref_impl/src/compiler/mir_ops.ts
ref_impl/src/interpreter/interpreter.ts
ref_impl/src/type_checker/type_checker.ts

Changes:
Add `_debug(...)` to support printing values out during testing, examples, or repl style environment. Will be disabled in any release builds.

Adding _debug(...) for debug printing

---

bosque-language-tools/language-configuration.json
bosque-language-tools/syntaxes/bosque.tmLanguage.json
ref_impl/src/ast/parser.ts

Fixes #90.
Changes:
The comment pattern has been changed. It'll capture single line and multi line comments.
VS Code support added.
Testing:
I've written few methods to test the functionality but haven't included in this PR because it's just a workaround. You can see [here](https://github.com/clegoz/BosqueLanguage/commit/59fe05221d0e9e56e480ed34684363ad73aab743)
If there's a way to test the lexer/parser, let me know, I'll be making changes gladly.

Multiline comments

---

ref_impl/src/ast/parser.ts

Fixes #127 
Changes:
I modified the `parseCompilationUnitPass2()` method in the `Parser` class to handle `EndOfStream` tokens and ensure that there are no illegal tokens.
Note:
I'm not sure if I modified the right method but after examining the `ast/parser.ts` file this one seemed the most appropriate.

Bugfix: Illegal tokens before the EOF are always getting ignored

---

ref_impl/src/test/app_tests.ts
ref_impl/src/test/apps/tictactoe/main.bsq
ref_impl/src/test/basic_evaluation_test.ts
ref_impl/src/test/library_tests.ts
ref_impl/src/test/regression_tests.ts
ref_impl/src/test/test_runner.ts

Changes:
Add unit test harness for running apps (and with different arguments) as part of standard suite.

Add test harness for apps as part of unit tests

---

bosque-language-tools/syntaxes/bosque.tmLanguage.json
docs/language/overview.md
ref_impl/src/ast/assembly.ts
ref_impl/src/ast/parser.ts
ref_impl/src/core/collections.bsq
ref_impl/src/core/core.bsq
ref_impl/src/interpreter/builtins.ts
ref_impl/src/interpreter/interpreter.ts
ref_impl/src/interpreter/value.ts
ref_impl/src/test/basic_evaluation_test.ts
ref_impl/src/type_checker/type_checker.ts

Changes:
Allow tuples and records in equality.
Update ckey to identity and change docs (still not implemented though).
Containers now use hash + equality and are stable on *insertion order*

Tweak equality and collections now stable on *insertion order*

---

ref_impl/src/test/app_runner.ts

Changes:
Currently, it seems any attempt to run `bin/test/app_runner.js`  needs to be in the `ref_impl` directory. I wanted to play around with some Bosque files located on my desktop, so I made a PowerShell alias to the compiler so I could just run it from the command line:
However, using this fails as `app_runner.ts` only looks in the current directory (in this case, the desktop) for the core files:
This PR makes Bosque look in the correct location regardless of where you call the compiler from, enabling aliases like the one above, so you don't have to fill the `ref_impl` directory with all your own files:
I also made the argument checking a little nicer for when the source file isn't provided as an argument:

Add directory insensitive use of app_runner

---

ref_impl/src/ast/body.ts
ref_impl/src/ast/parser.ts
ref_impl/src/compiler/mir_cleanup.ts
ref_impl/src/compiler/mir_emitter.ts
ref_impl/src/compiler/mir_ops.ts
ref_impl/src/compiler/mir_ssa.ts
ref_impl/src/interpreter/interpreter.ts
ref_impl/src/test/basic_evaluation_test.ts
ref_impl/src/type_checker/type_checker.ts
ref_impl/src/type_checker/type_environment.ts

Changes:
Add abort operation to MIR
Simplify other failures by emitting test/jump/abort ops

Add abort and simplify MIR ops to use it instead

---

ref_impl/src/core/core.bsq
ref_impl/src/interpreter/builtins.ts
ref_impl/src/test/library_tests.ts

related to #136 
Added arcus functions for sine and cosine to the math helper in core.

Add asin and acos functions to Math core

---

ref_impl/src/ast/assembly.ts

Fixes a missing issue in type checker. The tuple type `[Int, ?:Bool, Int]` does not make much sense with respect to an omitted second parameter. To address this we check that required parameters come before any optional parameters.

Fix for tuples with required params after optional

---

ref_impl/src/test/regression_tests.ts
ref_impl/src/type_checker/type_checker.ts

Fixes #192
Changes:
- Compare `param.name` with `pname` instead of `arg.name` when the parameter is expanded with spread operator.

Fix parameter mapping for records expanded with spread operator

---

bosque-language-tools/bsqdrop/core/cpp/list.bsq
bosque-language-tools/bsqdrop/core/symbolic/list.bsq
impl/src/core/cpp/list.bsq
impl/src/core/symbolic/list.bsq

Fixes https://github.com/microsoft/BosqueLanguage/issues/247
Changes:
This PR fixes a small bug in List's **sort** method by replacing the variable name `pf` with `cmp`.

fix: use correct variable name in List sort

---

impl/src/tooling/aot/cppbody_emitter.ts

Fixes https://github.com/microsoft/BosqueLanguage/issues/254
Changes:
This PR adds more detailed assertion information regarding not implemented methods.

[compiler] display more detailed assertions

---

impl/src/tooling/aot/cppbody_emitter.ts

Fixes https://github.com/microsoft/BosqueLanguage/issues/256
Changes:
Compilation of programs that use List's *max* method fails with an assertion error ("not implemented"). This PR fixes it by adding the missing **break** statement.

[compiler] fix fallthrough bug in list_max

---

impl/src/tooling/aot/cppbody_emitter.ts

Fixes https://github.com/microsoft/BosqueLanguage/issues/259
Changes:
Changes the else-clause from *"NSCore::Int"* to *"NSCore::BigInt"* in **list_sum**.

[compiler] use NSCore::BigInt in list_sum if-else clause

---

impl/src/core/cpp/map.bsq
impl/src/core/symbolic/map.bsq

Fixes https://github.com/microsoft/BosqueLanguage/issues/261
Changes:
Change variable name to "key".

[compiler] fix map.has(key) bug

---

impl/src/core/cpp/map.bsq
impl/src/core/symbolic/map.bsq

Fixes https://github.com/microsoft/BosqueLanguage/issues/263
Changes:
Changes the forwarded variable name to "key".

[compiler] fix map.get(key) bug

---

impl/src/ast/parser.ts
impl/src/tooling/aot/cppbody_emitter.ts
impl/src/tooling/aot/cpptype_emitter.ts
impl/src/tooling/bmc/runtime/smtruntime.smt2
impl/src/tooling/bmc/smtbody_emitter.ts
impl/src/tooling/bmc/smttype_emitter.ts

Fixes #249 
Changes:
Add partial support for identifiers.
Todo includes:
SymTest less operator generation for keys
Typechecker report error if explicit constructor is used instead of create.

Fix for identity basics

---

impl/src/ast/parser.ts
impl/src/tooling/aot/cppbody_emitter.ts
impl/src/tooling/aot/cpptype_emitter.ts
impl/src/tooling/aot/runtime/bsqkeyvalues.h
impl/src/tooling/aot/runtime/bsqvalue.cpp
impl/src/tooling/bmc/smtbody_emitter.ts

Fixes #275 #273
Changes:
Make Compound Key a value type (everywhere)
Fix bug in less code
Change constructor (create) to take the tuple/record instead of individual values

Compound identifiers fix and tweak design

---

impl/src/ast/parser.ts
impl/src/tooling/aot/cppbody_emitter.ts
impl/src/tooling/bmc/smtbody_emitter.ts

Revert partial of #274 -- keep original multi-arg signature for `create` method.

Revert CompoundKey create signature

---

impl/src/runtimes/exegen/README.md

I forgot to document the new `--flag` option for *exegen.js*.

[doc] added info on compiler --flags option for exegen

---

impl/src/test/tests/library/listtests.bsq
impl/src/tooling/aot/cppbody_emitter.ts
impl/src/tooling/aot/runtime/bsqcustom/bsqlist_ops.h

Fixes https://github.com/microsoft/BosqueLanguage/issues/290
Changes:
Implements List.sort. A test is also available. But it could be that my implementation is not the cleanest one, so please reject this PR if there is a better solution.
--EDIT: for now, only *less than* algorithm is supported as I am not sure how to properly "forward" the function given in the *sort* call.

added sort function for List

---

impl/src/tooling/aot/cppbody_emitter.ts

Fixes https://github.com/microsoft/BosqueLanguage/issues/296
Changes:
List.sort now accepts function parameter.

fix: make List.sort accept function param

---

impl/src/core/cpp/map.bsq
impl/src/core/symbolic/map.bsq

Fixes https://github.com/microsoft/BosqueLanguage/issues/302
Changes:
Map's **values()** methods from `cpp` and `symbolic` now have correct return value types.

fix: map's values function return type

---

impl/src/type_checker/type_checker.ts

There was a redundant semicolon right after **else {** in `checkArgumentsEvaluationWSig` from `type_checker.ts`.

trivial: remove redundant semicolon from else clause

---

impl/package-lock.json
impl/package.json
impl/scripts/make-exe.js

Fixes https://github.com/microsoft/BosqueLanguage/issues/251
Changes:
This PR adds a new npm script `make-exe` that allows installation of globally available `exegen.js` script on the three main platforms: Windows, macOS and Linux. 
This script combines three calls:
* compilation of exegen.js with `npm run build`
* conversion of exegen.js into an executable by the new script `make-exe.js` located in `impl/scripts`
* execution of the standard `npm link` command that creates a platform-independent global symlink.
The exegen script can be called with or without extension (`js` on macOS/Linux and `cmd` on Windows).
**Windows**
**macOS**
**Linux**

added script to make exegen.js globally available

---

impl/package-lock.json
impl/package.json
impl/scripts/make-exe.js

This PR removed the redundant npm package `chmod` from `make-exe` script.
Reference: https://github.com/microsoft/BosqueLanguage/issues/251#event-3445459405

remove redundant chmod npm package

---

impl/src/runtimes/exegen/exegen.ts
impl/src/runtimes/vscmd/vscmd.ts
impl/src/test/test_runner.ts

Fixes https://github.com/microsoft/BosqueLanguage/issues/335
Changes:
This PR removes fixed `clang` paths in Windows (`C:\Program Files\LLVM\bin`). As the compiler binary will be searched via the system PATH anyway, there is no need to hardcode it.

remove fixed clang paths in Windows

---

impl/src/core/verify/core.bsq
impl/src/core/verify/iteration.bsq
impl/src/core/verify/list.bsq
impl/src/core/verify/map.bsq
impl/src/core/verify/queue.bsq
impl/src/core/verify/set.bsq
impl/src/core/verify/stack.bsq
impl/src/runtimes/symtest/symtest.ts
impl/src/runtimes/vscmd/vscmd.ts
impl/src/test/runner.ts
impl/src/tooling/bmc/smtbody_emitter.ts
impl/src/tooling/bmc/smtdecls_emitter.ts

Changes:
`symtest` now supports a `--verify` option which replaces bounded symbolic testing with full verification using uninterpreted functions and axioms.
This PR mainly hooks up the right code and a default way to generate all the used uninterpreted functions but only has a few sample axioms so it isn't going to do a lot just yet.

Add initial support for verification

---

impl/src/runtimes/exegen/exegen.ts

Fixes https://github.com/microsoft/BosqueLanguage/issues/340
Changes:
This PR changes `exegen.ts` by adding a new feature that automatically appends the correct extension to the compiled binary according to OS under which it runs.

exegen: append default extension to compiled binary

---

docs/language/overview.md
impl/src/test/tests/doc_examples/langhighlight.bsq
impl/src/type_checker/type_checker.ts

Fixes #286 
Fixes #298 
Changes:
Add temporary checks for dead branches to avoid "ugly errors" these will eventually be an issue when compiling (with templates) since we want dead branches.
Later PR should provide a "safe compiler" and "warn IDE" flag to control how and if to treat these as errors.

Provide temporary dead code checks in Type Checker

---

bosque-language-tools/syntaxes/bosque.tmLanguage.json

**Changes:**
Perhaps we could specify the most common Bosque file type `bsq`

Set the filetype key in bosque.tmLanguage.json

---

impl/src/type_checker/type_checker.ts

Fixes: Names in ref parameters do not match (see PR#366)
Changes:
Get type info earlier and eliminate search based on matching names.

Fix type resolution in ref checking

---

impl/src/ast/parser.ts

Just a minor typo in parser output message.

trivial: typo in parser message

---

impl/src/compiler/mir_emitter.ts

Fixes #370 
Changes:
Ensure types A and B are both registered (in addition to just A&B).

fix for A&B static resolution

---

impl/src/tooling/aot/cppbody_emitter.ts

I tried to use the `Parse64::parse()` static method to parse arguments received from an Entrypoint, but I found error messages. 
So I discovered missing implementations in the cppbody_emitter. I'm not sure if this is an implementation aligned with the Bosque Roadmap, but it works.
I made this pull request to receive feedback about this proposal for performing this function.
TODO: Test cases

Fix: missing float64_parse implementation
